import type { WowRegion } from "@/types";

export interface Realm {
  name: string;
  slug: string;
}

const EU: Realm[] = [
  { name: "Aegwynn", slug: "aegwynn" },
  { name: "Aerie Peak", slug: "aerie-peak" },
  { name: "Agamaggan", slug: "agamaggan" },
  { name: "Aggra (Português)", slug: "aggra-portugues" },
  { name: "Aggramar", slug: "aggramar" },
  { name: "Ahn'Qiraj", slug: "ahn-qiraj" },
  { name: "Al'Akir", slug: "al-akir" },
  { name: "Alexstrasza", slug: "alexstrasza" },
  { name: "Alleria", slug: "alleria" },
  { name: "Alonsus", slug: "alonsus" },
  { name: "Aman'Thul", slug: "aman-thul" },
  { name: "Ambossar", slug: "ambossar" },
  { name: "Anachronos", slug: "anachronos" },
  { name: "Anetheron", slug: "anetheron" },
  { name: "Antonidas", slug: "antonidas" },
  { name: "Anub'arak", slug: "anub-arak" },
  { name: "Anvilmar", slug: "anvilmar" },
  { name: "Arathor", slug: "arathor" },
  { name: "Archimonde", slug: "archimonde" },
  { name: "Area 52", slug: "area-52" },
  { name: "Argent Dawn", slug: "argent-dawn" },
  { name: "Arthas", slug: "arthas" },
  { name: "Arygos", slug: "arygos" },
  { name: "Aszune", slug: "aszune" },
  { name: "Auchindoun", slug: "auchindoun" },
  { name: "Azjol-Nerub", slug: "azjol-nerub" },
  { name: "Azshara", slug: "azshara" },
  { name: "Azuregos", slug: "azuregos" },
  { name: "Azuremyst", slug: "azuremyst" },
  { name: "Baelgun", slug: "baelgun" },
  { name: "Balnazzar", slug: "balnazzar" },
  { name: "Blackhand", slug: "blackhand" },
  { name: "Blackmoore", slug: "blackmoore" },
  { name: "Blackrock", slug: "blackrock" },
  { name: "Blade's Edge", slug: "blades-edge" },
  { name: "Bladefist", slug: "bladefist" },
  { name: "Bloodfeather", slug: "bloodfeather" },
  { name: "Bloodhoof", slug: "bloodhoof" },
  { name: "Bloodscalp", slug: "bloodscalp" },
  { name: "Boulderfist", slug: "boulderfist" },
  { name: "Bronze Dragonflight", slug: "bronze-dragonflight" },
  { name: "Bronzebeard", slug: "bronzebeard" },
  { name: "Burning Blade", slug: "burning-blade" },
  { name: "Burning Legion", slug: "burning-legion" },
  { name: "Burning Steppes", slug: "burning-steppes" },
  { name: "C'Thun", slug: "c-thun" },
  { name: "Chamber of Aspects", slug: "chamber-of-aspects" },
  { name: "Chants éternels", slug: "chants-eternels" },
  { name: "Cho'gall", slug: "cho-gall" },
  { name: "Chromaggus", slug: "chromaggus" },
  { name: "Colinas Pardas", slug: "colinas-pardas" },
  { name: "Confrérie du Thorium", slug: "confrerie-du-thorium" },
  { name: "Conseil des Ombres", slug: "conseil-des-ombres" },
  { name: "Crushridge", slug: "crushridge" },
  { name: "Culte de la Rive noire", slug: "culte-de-la-rive-noire" },
  { name: "Daggerspine", slug: "daggerspine" },
  { name: "Dalaran", slug: "dalaran" },
  { name: "Dalvengyr", slug: "dalvengyr" },
  { name: "Darkmoon Faire", slug: "darkmoon-faire" },
  { name: "Darksorrow", slug: "darksorrow" },
  { name: "Darkspear", slug: "darkspear" },
  { name: "Das Konsortium", slug: "das-konsortium" },
  { name: "Das Syndikat", slug: "das-syndikat" },
  { name: "Deathwing", slug: "deathwing" },
  { name: "Defias Brotherhood", slug: "defias-brotherhood" },
  { name: "Dentarg", slug: "dentarg" },
  { name: "Der abyssische Rat", slug: "der-abyssische-rat" },
  { name: "Der Rat von Dalaran", slug: "der-rat-von-dalaran" },
  { name: "Destromath", slug: "destromath" },
  { name: "Dethecus", slug: "dethecus" },
  { name: "Die Aldor", slug: "die-aldor" },
  { name: "Die Arguswacht", slug: "die-arguswacht" },
  { name: "Die ewige Wacht", slug: "die-ewige-wacht" },
  { name: "Die Nachtwache", slug: "die-nachtwache" },
  { name: "Die Silberne Hand", slug: "die-silberne-hand" },
  { name: "Die Todeskrallen", slug: "die-todeskrallen" },
  { name: "Die Traumweber", slug: "die-traumweber" },
  { name: "Doomhammer", slug: "doomhammer" },
  { name: "Draenor", slug: "draenor" },
  { name: "Dragonblight", slug: "dragonblight" },
  { name: "Dragonmaw", slug: "dragonmaw" },
  { name: "Drak'thul", slug: "drak-thul" },
  { name: "Drakkar", slug: "drakkar" },
  { name: "Draka", slug: "draka" },
  { name: "Drenden", slug: "drenden" },
  { name: "Dunemaul", slug: "dunemaul" },
  { name: "Durotan", slug: "durotan" },
  { name: "Earthen Ring", slug: "earthen-ring" },
  { name: "Echsenkessel", slug: "echsenkessel" },
  { name: "Eitrigg", slug: "eitrigg" },
  { name: "Eldre'Thalas", slug: "eldre-thalas" },
  { name: "Emerald Dream", slug: "emerald-dream" },
  { name: "Emeriss", slug: "emeriss" },
  { name: "Eonar", slug: "eonar" },
  { name: "Eredar", slug: "eredar" },
  { name: "Eu.Stormscale", slug: "stormscale" },
  { name: "Executus", slug: "executus" },
  { name: "Exodar", slug: "exodar" },
  { name: "Festung der Stürme", slug: "festung-der-sturme" },
  { name: "Fordragon", slug: "fordragon" },
  { name: "Forscherliga", slug: "forscherliga" },
  { name: "Frostmane", slug: "frostmane" },
  { name: "Frostmourne", slug: "frostmourne" },
  { name: "Frostwolf", slug: "frostwolf" },
  { name: "Galakrond", slug: "galakrond" },
  { name: "Garona", slug: "garona" },
  { name: "Garrosh", slug: "garrosh" },
  { name: "Genjuros", slug: "genjuros" },
  { name: "Ghostlands", slug: "ghostlands" },
  { name: "Gilneas", slug: "gilneas" },
  { name: "Gorgonnash", slug: "gorgonnash" },
  { name: "Greymane", slug: "greymane" },
  { name: "Grizzly Hills", slug: "grizzly-hills" },
  { name: "Grim Batol", slug: "grim-batol" },
  { name: "Gul'dan", slug: "gul-dan" },
  { name: "Gurubashi", slug: "gurubashi" },
  { name: "Hakkar", slug: "hakkar" },
  { name: "Haomarush", slug: "haomarush" },
  { name: "Hellfire", slug: "hellfire" },
  { name: "Hellscream", slug: "hellscream" },
  { name: "Hyjal", slug: "hyjal" },
  { name: "Illidan", slug: "illidan" },
  { name: "Jaedenar", slug: "jaedenar" },
  { name: "Karazhan", slug: "karazhan" },
  { name: "Kargath", slug: "kargath" },
  { name: "Kaz'goroth", slug: "kaz-goroth" },
  { name: "Kazzak", slug: "kazzak" },
  { name: "Kezan", slug: "kezan" },
  { name: "Kil'Jaeden", slug: "kil-jaeden" },
  { name: "Kilrogg", slug: "kilrogg" },
  { name: "Kirin Tor", slug: "kirin-tor" },
  { name: "Kor'gall", slug: "kor-gall" },
  { name: "Krag'jin", slug: "krag-jin" },
  { name: "Krasus", slug: "krasus" },
  { name: "Kul Tiras", slug: "kul-tiras" },
  { name: "Kulindor", slug: "kulindor" },
  { name: "La Croisade écarlate", slug: "la-croisade-ecarlate" },
  { name: "Laughing Skull", slug: "laughing-skull" },
  { name: "Les Clairvoyants", slug: "les-clairvoyants" },
  { name: "Les Sentinelles", slug: "les-sentinelles" },
  { name: "Lightbringer", slug: "lightbringer" },
  { name: "Lightning's Blade", slug: "lightnings-blade" },
  { name: "Lordaeron", slug: "lordaeron" },
  { name: "Los Errantes", slug: "los-errantes" },
  { name: "Lothar", slug: "lothar" },
  { name: "Madmortem", slug: "madmortem" },
  { name: "Magtheridon", slug: "magtheridon" },
  { name: "Mal'Ganis", slug: "mal-ganis" },
  { name: "Malfurion", slug: "malfurion" },
  { name: "Malorne", slug: "malorne" },
  { name: "Malygos", slug: "malygos" },
  { name: "Mannoroth", slug: "mannoroth" },
  { name: "Marek Bronzebeard", slug: "marek-bronzebeard" },
  { name: "Mazrigos", slug: "mazrigos" },
  { name: "Medivh", slug: "medivh" },
  { name: "Minahonda", slug: "minahonda" },
  { name: "Moonglade", slug: "moonglade" },
  { name: "Moonsong", slug: "moonsong" },
  { name: "Mug'thol", slug: "mug-thol" },
  { name: "Nagrand", slug: "nagrand" },
  { name: "Nathrezim", slug: "nathrezim" },
  { name: "Naxxramas", slug: "naxxramas" },
  { name: "Nazjatar", slug: "nazjatar" },
  { name: "Nefarian", slug: "nefarian" },
  { name: "Nemesis", slug: "nemesis" },
  { name: "Neptulon", slug: "neptulon" },
  { name: "Nera'thor", slug: "nera-thor" },
  { name: "Nethersturm", slug: "nethersturm" },
  { name: "Nordrassil", slug: "nordrassil" },
  { name: "Norgannon", slug: "norgannon" },
  { name: "Nozdormu", slug: "nozdormu" },
  { name: "Onyxia", slug: "onyxia" },
  { name: "Outland", slug: "outland" },
  { name: "Perenolde", slug: "perenolde" },
  { name: "Pozzo dell'Eternità", slug: "pozzo-dell-eternita" },
  { name: "Proudmoore", slug: "proudmoore" },
  { name: "Quel'Thalas", slug: "quel-thalas" },
  { name: "Ragnaros", slug: "ragnaros" },
  { name: "Rashgarroth", slug: "rashgarroth" },
  { name: "Ravencrest", slug: "ravencrest" },
  { name: "Ravenholdt", slug: "ravenholdt" },
  { name: "Rexxar", slug: "rexxar" },
  { name: "Runetotem", slug: "runetotem" },
  { name: "Sanguino", slug: "sanguino" },
  { name: "Sargeras", slug: "sargeras" },
  { name: "Saurfang", slug: "saurfang" },
  { name: "Scarshield Legion", slug: "scarshield-legion" },
  { name: "Sen'jin", slug: "sen-jin" },
  { name: "Shadowmoon", slug: "shadowmoon" },
  { name: "Shattered Halls", slug: "shattered-halls" },
  { name: "Shattered Hand", slug: "shattered-hand" },
  { name: "Shattrath", slug: "shattrath" },
  { name: "Shen'dralar", slug: "shen-dralar" },
  { name: "Silvermoon", slug: "silvermoon" },
  { name: "Sinstralis", slug: "sinstralis" },
  { name: "Skullcrusher", slug: "skullcrusher" },
  { name: "Soulflayer", slug: "soulflayer" },
  { name: "Spinebreaker", slug: "spinebreaker" },
  { name: "Sporeggar", slug: "sporeggar" },
  { name: "Steamwheedle Cartel", slug: "steamwheedle-cartel" },
  { name: "Stormreaver", slug: "stormreaver" },
  { name: "Stormscale", slug: "stormscale" },
  { name: "Sunstrider", slug: "sunstrider" },
  { name: "Sylvanas", slug: "sylvanas" },
  { name: "Taerar", slug: "taerar" },
  { name: "Talnivarr", slug: "talnivarr" },
  { name: "Tarren Mill", slug: "tarren-mill" },
  { name: "Teldrassil", slug: "teldrassil" },
  { name: "Temple noir", slug: "temple-noir" },
  { name: "Terenas", slug: "terenas" },
  { name: "Terokkar", slug: "terokkar" },
  { name: "Terrordar", slug: "terrordar" },
  { name: "The Maelstrom", slug: "the-maelstrom" },
  { name: "The Sha'tar", slug: "the-sha-tar" },
  { name: "The Venture Co", slug: "the-venture-co" },
  { name: "Theradras", slug: "theradras" },
  { name: "Thrall", slug: "thrall" },
  { name: "Throk'Feroth", slug: "throk-feroth" },
  { name: "Thunderhorn", slug: "thunderhorn" },
  { name: "Tichondrius", slug: "tichondrius" },
  { name: "Tirion", slug: "tirion" },
  { name: "Todeswache", slug: "todeswache" },
  { name: "Trollbane", slug: "trollbane" },
  { name: "Turalyon", slug: "turalyon" },
  { name: "Twisting Nether", slug: "twisting-nether" },
  { name: "Tyrande", slug: "tyrande" },
  { name: "Uldaman", slug: "uldaman" },
  { name: "Ulduar", slug: "ulduar" },
  { name: "Uldum", slug: "uldum" },
  { name: "Un'Goro", slug: "un-goro" },
  { name: "Undermine", slug: "undermine" },
  { name: "Vashj", slug: "vashj" },
  { name: "Vek'lor", slug: "vek-lor" },
  { name: "Vek'nilash", slug: "vek-nilash" },
  { name: "Vol'jin", slug: "vol-jin" },
  { name: "Wildhammer", slug: "wildhammer" },
  { name: "Wrathbringer", slug: "wrathbringer" },
  { name: "Xavius", slug: "xavius" },
  { name: "Ysera", slug: "ysera" },
  { name: "Ysondre", slug: "ysondre" },
  { name: "Zenedar", slug: "zenedar" },
  { name: "Zirkel des Cenarius", slug: "zirkel-des-cenarius" },
  { name: "Zuluhed", slug: "zuluhed" },
  { name: "Zul'jin", slug: "zul-jin" },
  { name: "Zuram", slug: "zuram" },
];

const US: Realm[] = [
  { name: "Aegwynn", slug: "aegwynn" },
  { name: "Aerie Peak", slug: "aerie-peak" },
  { name: "Agamaggan", slug: "agamaggan" },
  { name: "Aggramar", slug: "aggramar" },
  { name: "Akama", slug: "akama" },
  { name: "Alexstrasza", slug: "alexstrasza" },
  { name: "Alleria", slug: "alleria" },
  { name: "Altar of Storms", slug: "altar-of-storms" },
  { name: "Alterac Mountains", slug: "alterac-mountains" },
  { name: "Aman'Thul", slug: "aman-thul" },
  { name: "Andorhal", slug: "andorhal" },
  { name: "Anetheron", slug: "anetheron" },
  { name: "Antonidas", slug: "antonidas" },
  { name: "Anub'arak", slug: "anub-arak" },
  { name: "Anvilmar", slug: "anvilmar" },
  { name: "Arathor", slug: "arathor" },
  { name: "Archimonde", slug: "archimonde" },
  { name: "Area 52", slug: "area-52" },
  { name: "Argent Dawn", slug: "argent-dawn" },
  { name: "Arthas", slug: "arthas" },
  { name: "Arygos", slug: "arygos" },
  { name: "Auchindoun", slug: "auchindoun" },
  { name: "Azgalor", slug: "azgalor" },
  { name: "Azjol-Nerub", slug: "azjol-nerub" },
  { name: "Azralon", slug: "azralon" },
  { name: "Azshara", slug: "azshara" },
  { name: "Azuremyst", slug: "azuremyst" },
  { name: "Baelgun", slug: "baelgun" },
  { name: "Balnazzar", slug: "balnazzar" },
  { name: "Barthilas", slug: "barthilas" },
  { name: "Black Dragonflight", slug: "black-dragonflight" },
  { name: "Blackhand", slug: "blackhand" },
  { name: "Blackrock", slug: "blackrock" },
  { name: "Blackwater Raiders", slug: "blackwater-raiders" },
  { name: "Blackwing Lair", slug: "blackwing-lair" },
  { name: "Blade's Edge", slug: "blades-edge" },
  { name: "Bladefist", slug: "bladefist" },
  { name: "Bleeding Hollow", slug: "bleeding-hollow" },
  { name: "Blood Furnace", slug: "blood-furnace" },
  { name: "Bloodhoof", slug: "bloodhoof" },
  { name: "Bloodscalp", slug: "bloodscalp" },
  { name: "Bonechewer", slug: "bonechewer" },
  { name: "Borean Tundra", slug: "borean-tundra" },
  { name: "Boulderfist", slug: "boulderfist" },
  { name: "Bronze Dragonflight", slug: "bronze-dragonflight" },
  { name: "Bronzebeard", slug: "bronzebeard" },
  { name: "Burning Blade", slug: "burning-blade" },
  { name: "Burning Legion", slug: "burning-legion" },
  { name: "Caelestrasz", slug: "caelestrasz" },
  { name: "Cairne", slug: "cairne" },
  { name: "Cenarion Circle", slug: "cenarion-circle" },
  { name: "Cenarion Expedition", slug: "cenarion-expedition" },
  { name: "Cho'gall", slug: "cho-gall" },
  { name: "Chromaggus", slug: "chromaggus" },
  { name: "Coilfang", slug: "coilfang" },
  { name: "Crushridge", slug: "crushridge" },
  { name: "Daggerspine", slug: "daggerspine" },
  { name: "Dalaran", slug: "dalaran" },
  { name: "Dalvengyr", slug: "dalvengyr" },
  { name: "Dark Iron", slug: "dark-iron" },
  { name: "Darkspear", slug: "darkspear" },
  { name: "Darrowmere", slug: "darrowmere" },
  { name: "Dath'Remar", slug: "dath-remar" },
  { name: "Dawnbringer", slug: "dawnbringer" },
  { name: "Deathwing", slug: "deathwing" },
  { name: "Dentarg", slug: "dentarg" },
  { name: "Destromath", slug: "destromath" },
  { name: "Detheroc", slug: "detheroc" },
  { name: "Doomhammer", slug: "doomhammer" },
  { name: "Draenor", slug: "draenor" },
  { name: "Dragonblight", slug: "dragonblight" },
  { name: "Dragonmaw", slug: "dragonmaw" },
  { name: "Drak'Tharon", slug: "drak-tharon" },
  { name: "Drak'thul", slug: "drak-thul" },
  { name: "Draka", slug: "draka" },
  { name: "Drenden", slug: "drenden" },
  { name: "Dunemaul", slug: "dunemaul" },
  { name: "Durotan", slug: "durotan" },
  { name: "Duskwood", slug: "duskwood" },
  { name: "Earthen Ring", slug: "earthen-ring" },
  { name: "Echo Isles", slug: "echo-isles" },
  { name: "Eitrigg", slug: "eitrigg" },
  { name: "Eldre'Thalas", slug: "eldre-thalas" },
  { name: "Elune", slug: "elune" },
  { name: "Emerald Dream", slug: "emerald-dream" },
  { name: "Eonar", slug: "eonar" },
  { name: "Eredar", slug: "eredar" },
  { name: "Executus", slug: "executus" },
  { name: "Exodar", slug: "exodar" },
  { name: "Farstriders", slug: "farstriders" },
  { name: "Feathermoon", slug: "feathermoon" },
  { name: "Fenris", slug: "fenris" },
  { name: "Firetree", slug: "firetree" },
  { name: "Fizzcrank", slug: "fizzcrank" },
  { name: "Frostmane", slug: "frostmane" },
  { name: "Frostmourne", slug: "frostmourne" },
  { name: "Frostwolf", slug: "frostwolf" },
  { name: "Galakrond", slug: "galakrond" },
  { name: "Gallywix", slug: "gallywix" },
  { name: "Garona", slug: "garona" },
  { name: "Garrosh", slug: "garrosh" },
  { name: "Ghostlands", slug: "ghostlands" },
  { name: "Gilneas", slug: "gilneas" },
  { name: "Gnomeregan", slug: "gnomeregan" },
  { name: "Goldrinn", slug: "goldrinn" },
  { name: "Greymane", slug: "greymane" },
  { name: "Grizzly Hills", slug: "grizzly-hills" },
  { name: "Gul'dan", slug: "gul-dan" },
  { name: "Gurubashi", slug: "gurubashi" },
  { name: "Hakkar", slug: "hakkar" },
  { name: "Haomarush", slug: "haomarush" },
  { name: "Hellscream", slug: "hellscream" },
  { name: "Hydraxis", slug: "hydraxis" },
  { name: "Hyjal", slug: "hyjal" },
  { name: "Icecrown", slug: "icecrown" },
  { name: "Illidan", slug: "illidan" },
  { name: "Jaedenar", slug: "jaedenar" },
  { name: "Jubei'Thos", slug: "jubei-thos" },
  { name: "Kael'thas", slug: "kael-thas" },
  { name: "Kalecgos", slug: "kalecgos" },
  { name: "Kargath", slug: "kargath" },
  { name: "Kaz'goroth", slug: "kaz-goroth" },
  { name: "Khadgar", slug: "khadgar" },
  { name: "Khaz Modan", slug: "khaz-modan" },
  { name: "Khaz'goroth", slug: "khaz-goroth" },
  { name: "Kil'Jaeden", slug: "kil-jaeden" },
  { name: "Kilrogg", slug: "kilrogg" },
  { name: "Kirin Tor", slug: "kirin-tor" },
  { name: "Korgath", slug: "korgath" },
  { name: "Kul Tiras", slug: "kul-tiras" },
  { name: "Laughing Skull", slug: "laughing-skull" },
  { name: "Lightbringer", slug: "lightbringer" },
  { name: "Lightning's Blade", slug: "lightnings-blade" },
  { name: "Lightninghoof", slug: "lightninghoof" },
  { name: "Llane", slug: "llane" },
  { name: "Lothar", slug: "lothar" },
  { name: "Madoran", slug: "madoran" },
  { name: "Maelstrom", slug: "maelstrom" },
  { name: "Magtheridon", slug: "magtheridon" },
  { name: "Mal'Ganis", slug: "mal-ganis" },
  { name: "Malfurion", slug: "malfurion" },
  { name: "Malorne", slug: "malorne" },
  { name: "Malygos", slug: "malygos" },
  { name: "Mannoroth", slug: "mannoroth" },
  { name: "Medivh", slug: "medivh" },
  { name: "Misha", slug: "misha" },
  { name: "Mok'Nathal", slug: "mok-nathal" },
  { name: "Moon Guard", slug: "moon-guard" },
  { name: "Moonrunner", slug: "moonrunner" },
  { name: "Mug'thol", slug: "mug-thol" },
  { name: "Muradin", slug: "muradin" },
  { name: "Nagrand", slug: "nagrand" },
  { name: "Nathrezim", slug: "nathrezim" },
  { name: "Nazgrel", slug: "nazgrel" },
  { name: "Nazjatar", slug: "nazjatar" },
  { name: "Nefarian", slug: "nefarian" },
  { name: "Nemesis", slug: "nemesis" },
  { name: "Neptulon", slug: "neptulon" },
  { name: "Ner'zhul", slug: "ner-zhul" },
  { name: "Nesingwary", slug: "nesingwary" },
  { name: "Nordrassil", slug: "nordrassil" },
  { name: "Norgannon", slug: "norgannon" },
  { name: "Onyxia", slug: "onyxia" },
  { name: "Perenolde", slug: "perenolde" },
  { name: "Proudmoore", slug: "proudmoore" },
  { name: "Quel'dorei", slug: "quel-dorei" },
  { name: "Quel'Thalas", slug: "quel-thalas" },
  { name: "Ragnaros", slug: "ragnaros" },
  { name: "Ravencrest", slug: "ravencrest" },
  { name: "Ravenholdt", slug: "ravenholdt" },
  { name: "Rexxar", slug: "rexxar" },
  { name: "Rivendare", slug: "rivendare" },
  { name: "Runetotem", slug: "runetotem" },
  { name: "Sargeras", slug: "sargeras" },
  { name: "Saurfang", slug: "saurfang" },
  { name: "Scarlet Crusade", slug: "scarlet-crusade" },
  { name: "Sen'jin", slug: "sen-jin" },
  { name: "Shadow Council", slug: "shadow-council" },
  { name: "Shadowmoon", slug: "shadowmoon" },
  { name: "Shadowsong", slug: "shadowsong" },
  { name: "Shattered Halls", slug: "shattered-halls" },
  { name: "Shattered Hand", slug: "shattered-hand" },
  { name: "Silver Hand", slug: "silver-hand" },
  { name: "Silvermoon", slug: "silvermoon" },
  { name: "Skullcrusher", slug: "skullcrusher" },
  { name: "Skywall", slug: "skywall" },
  { name: "Smolderthorn", slug: "smolderthorn" },
  { name: "Spinebreaker", slug: "spinebreaker" },
  { name: "Spirestone", slug: "spirestone" },
  { name: "Staghelm", slug: "staghelm" },
  { name: "Steamwheedle Cartel", slug: "steamwheedle-cartel" },
  { name: "Stonemaul", slug: "stonemaul" },
  { name: "Stormrage", slug: "stormrage" },
  { name: "Stormreaver", slug: "stormreaver" },
  { name: "Stormscale", slug: "stormscale" },
  { name: "Suramar", slug: "suramar" },
  { name: "Tanaris", slug: "tanaris" },
  { name: "Tarren Mill", slug: "tarren-mill" },
  { name: "Teldrassil", slug: "teldrassil" },
  { name: "Terenas", slug: "terenas" },
  { name: "Terokkar", slug: "terokkar" },
  { name: "The Forgotten Coast", slug: "the-forgotten-coast" },
  { name: "The Scryers", slug: "the-scryers" },
  { name: "The Underbog", slug: "the-underbog" },
  { name: "The Venture Co", slug: "the-venture-co" },
  { name: "Thorium Brotherhood", slug: "thorium-brotherhood" },
  { name: "Thrall", slug: "thrall" },
  { name: "Thunderhorn", slug: "thunderhorn" },
  { name: "Thunderlord", slug: "thunderlord" },
  { name: "Tichondrius", slug: "tichondrius" },
  { name: "Tirion", slug: "tirion" },
  { name: "Tol Barad", slug: "tol-barad" },
  { name: "Tortheldrin", slug: "tortheldrin" },
  { name: "Trollbane", slug: "trollbane" },
  { name: "Turalyon", slug: "turalyon" },
  { name: "Twisting Nether", slug: "twisting-nether" },
  { name: "Tyrande", slug: "tyrande" },
  { name: "Uldaman", slug: "uldaman" },
  { name: "Uldum", slug: "uldum" },
  { name: "Undermine", slug: "undermine" },
  { name: "Ursin", slug: "ursin" },
  { name: "Uther", slug: "uther" },
  { name: "Vashj", slug: "vashj" },
  { name: "Velen", slug: "velen" },
  { name: "Warsong", slug: "warsong" },
  { name: "Whisperwind", slug: "whisperwind" },
  { name: "Wildhammer", slug: "wildhammer" },
  { name: "Windrunner", slug: "windrunner" },
  { name: "Winterhoof", slug: "winterhoof" },
  { name: "Wyrmrest Accord", slug: "wyrmrest-accord" },
  { name: "Xavius", slug: "xavius" },
  { name: "Ysera", slug: "ysera" },
  { name: "Ysondre", slug: "ysondre" },
  { name: "Zangarmarsh", slug: "zangarmarsh" },
  { name: "Zuluhed", slug: "zuluhed" },
  { name: "Zul'jin", slug: "zul-jin" },
  { name: "Zul'Aman", slug: "zul-aman" },
];

const KR: Realm[] = [
  { name: "Azshara", slug: "azshara" },
  { name: "Burning Legion", slug: "burning-legion" },
  { name: "Cenarius", slug: "cenarius" },
  { name: "Durotan", slug: "durotan" },
  { name: "Garona", slug: "garona" },
  { name: "Hellscream", slug: "hellscream" },
  { name: "Hyjal", slug: "hyjal" },
  { name: "Kargath", slug: "kargath" },
  { name: "Malfurion", slug: "malfurion" },
  { name: "Norgannon", slug: "norgannon" },
  { name: "Stormrage", slug: "stormrage" },
  { name: "Wildhammer", slug: "wildhammer" },
  { name: "Windrunner", slug: "windrunner" },
];

const TW: Realm[] = [
  { name: "Arthas", slug: "arthas" },
  { name: "Arygos", slug: "arygos" },
  { name: "Bleeding Hollow", slug: "bleeding-hollow" },
  { name: "Chillwind Point", slug: "chillwind-point" },
  { name: "Crystalpine Stinger", slug: "crystalpine-stinger" },
  { name: "Demon Fall Canyon", slug: "demon-fall-canyon" },
  { name: "Dragonmaw", slug: "dragonmaw" },
  { name: "Frostmourne", slug: "frostmourne" },
  { name: "Galakrond", slug: "galakrond" },
  { name: "Hellscream", slug: "hellscream" },
  { name: "Light's Hope", slug: "lights-hope" },
  { name: "Menethil", slug: "menethil" },
  { name: "Nightsong", slug: "nightsong" },
  { name: "Quel'dorei", slug: "quel-dorei" },
  { name: "Ravencrest", slug: "ravencrest" },
  { name: "Shadowmoon", slug: "shadowmoon" },
  { name: "Skywall", slug: "skywall" },
  { name: "Spirestone", slug: "spirestone" },
  { name: "Stormscale", slug: "stormscale" },
  { name: "Sundown Marsh", slug: "sundown-marsh" },
  { name: "Thunder", slug: "thunder" },
  { name: "Wrathbringer", slug: "wrathbringer" },
];

export const REALMS: Record<WowRegion, Realm[]> = { eu: EU, us: US, kr: KR, tw: TW };

export function getRealms(region: WowRegion): Realm[] {
  return REALMS[region] ?? [];
}
